[package]
name = "learn_wgpu"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["renderer"]

[dependencies]
pollster = "0.3.0"
renderer = { path = "./renderer" }
wgpu = { version = "0.18.0", features = ["glsl"] }
